

rule other:
    output:
        touch("b.txt")


rule seqtk_seq_fastq_to_fasta:
    input:
        "{prefix}.fastq",
    output:
        "{prefix}.fasta",
    params:
        extra="-A",
    wrapper:
        "v1.25.0/bio/seqtk/seq"