from snakemake.utils import min_version
min_version("6.0")


rule some_rule:
    output:
        touch("a.fastq")


module other_workflow:
    snakefile:
        # here, plain paths, URLs and the special markers for code hosting providers (see below) are possible.
        "../workflow2/Snakefile"

use rule * from other_workflow



